mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/shiro?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  redisson:
    #address: redis://192.168.242.128:6379
    address: redis://127.0.0.1:6379
  profiles:
    active: dev
  application:
    name: selfProject
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

logging:
  level:
    com:
      looedu:
        mapper: debug
  path: E:/log
  file: my.log
server:
  port: 8085
shiro:
  cas: http://95.169.6.84:8088/cas
  server: http://127.0.0.1:8085

mapper:
  mappers: com.djz.common.base.mapper.BaseMapper
  not-empty: false
  identity: mysql


