-- 用户表
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
	ID BIGINT NOT NULL , -- ID
	CODE VARCHAR(100) NOT NULL, -- 编码
	USER_NAME VARCHAR(100) NOT NULL,-- 登录账号
	REAL_NAME VARCHAR(100),-- 真实姓名
	PASSWORD VARCHAR(100) NOT NULL,-- 登录密码
	AGE INT,-- 年龄
	EMAIL VARCHAR(50),-- 邮箱
	SEX  SMALLINT,-- 性别
	PHONE VARCHAR(50),-- 电话
	CREATOR_ID VARCHAR(100),-- 创建人ID
	UPDATOR_ID VARCHAR(100),-- 操作人ID
	CREATOR_NAME VARCHAR(100),-- 创建人名称
	OPERATOR_NAME VARCHAR(100),-- 操作人名称
	DEFAULT_THEME VARCHAR(100), -- 默认主题
	LAST_IP VARCHAR(100), -- 最后登录IP
	LAST_TIME DATETIME,-- 最后登录时间
	CREATE_TIME DATETIME,-- 创建时间
	OPERATE_TIME DATETIME,-- 操作时间
	STATUS SMALLINT,-- 状态
	SUPERMAN SMALLINT,-- 是否是超级管理员
	PRIMARY KEY (ID)
);


-- 角色表
DROP TABLE IF EXISTS SYS_ROLE;
CREATE TABLE SYS_ROLE (
	ID BIGINT NOT NULL , -- ID
	CODE VARCHAR(100)  NULL, -- 编码
	ROLE_NAME VARCHAR(50) NOT NULL , -- 角色名称
	REMARK LONGTEXT, -- 描述，备注
	DISPLAY_ORDER  DECIMAL(18,2) NULL , -- 展示顺序
	CREATOR_ID VARCHAR(100),-- 创建人ID
	UPDATOR_ID VARCHAR(100),-- 操作人ID
	CREATOR_NAME VARCHAR(100),-- 创建人名称
	OPERATOR_NAME VARCHAR(100),-- 操作人名称
	CREATE_TIME DATETIME,-- 创建时间
	OPERATE_TIME DATETIME,-- 操作时间
	STATUS SMALLINT,-- 状态
	PRIMARY KEY (ID)
);

-- 资源权限表
DROP TABLE IF EXISTS SYS_RESOURCE;
CREATE TABLE SYS_RESOURCE (
	ID BIGINT NOT NULL , -- ID
	CODE VARCHAR(100)  NULL, -- 编码
	PARENTID BIGINT NULL , -- 父ID
	PARENT_CODE  VARCHAR(100)  NULL ,  -- 父编码
	PATH VARCHAR(255) ,-- 路径
	RESOURCENAME VARCHAR(50) NOT NULL ,-- 资源名称
	URL VARCHAR(200) , -- url
	URLPREFIX VARCHAR(200) , -- url 前缀
	REMARK VARCHAR(2000) , -- 描述，备注
	ROUTETYPE VARCHAR(20) ,-- 路由类型
	MODULEPATH VARCHAR(2000) , -- 模块路径
	IMAGE VARCHAR(5000) , -- 图片
	RESOURCETYPE VARCHAR(20)  NOT NULL , -- 资源类型
	PERMISSION VARCHAR(100) , -- 权限
	DISPLAYORDER DECIMAL(18,2) NULL , -- 展示顺序
	NODELEVEL INT NULL , -- 节点等级
	MODULEMETHOD VARCHAR(20), -- 模块方法
	URLTARGET VARCHAR(20) , -- URLTARGET 
	SYS  SMALLINT NOT NULL DEFAULT 0, -- 是否系统默认
	CREATOR_ID VARCHAR(100),-- 创建人ID
	UPDATOR_ID VARCHAR(100),-- 操作人ID
	CREATOR_NAME VARCHAR(100),-- 创建人名称
	OPERATOR_NAME VARCHAR(100),-- 操作人名称
	CREATE_TIME DATETIME,-- 创建时间
	OPERATE_TIME DATETIME,-- 操作时间
	STATUS SMALLINT,-- 状态
	PRIMARY KEY (ID)
);

-- 用户角色中间表
DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE  SYS_USER_ROLE(
	USERID BIGINT NOT NULL ,
	ROLEID BIGINT NOT NULL 
);

-- 角色权限中间表
DROP TABLE IF EXISTS SYS_ROLE_RESOURCE;
CREATE TABLE  SYS_ROLE_RESOURCE(
	ROLEID BIGINT NOT NULL ,
	RESOURCEID BIGINT NOT NULL 
);
 