-- 用户表
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
	ID VARCHAR(100) NOT NULL, -- ID
	CODE VARCHAR(100) NOT NULL, -- 编码
	USER_NAME VARCHAR(100) NOT NULL,-- 登录账号
	REAL_NAME VARCHAR(100),-- 真实姓名
	PASSWORD VARCHAR(100) NOT NULL,-- 登录密码
	AGE INT,-- 年龄
	EMAIL VARCHAR(50),-- 邮箱
	SEX  BIT(1),-- 性别
	PHONE VARCHAR(50),-- 电话
	CREATOR_ID VARCHAR(100),-- 创建人ID
	UPDATOR_ID VARCHAR(100),-- 操作人ID
	CREATOR_NAME VARCHAR(100),-- 创建人名称
	OPERATOR_NAME VARCHAR(100),-- 操作人名称
	DEFAULT_THEME VARCHAR(100), -- 默认主题
	LAST_IP VARCHAR(100), -- 最后登录IP
	LAST_TIME DATETIME,-- 最后登录时间
	CREATE_TIME DATETIME,-- 创建时间
	OPERATE_TIME DATETIME,-- 修改时候
	STATUS BIT(1),-- 状态
	SUPERMAN BIT(1),-- 是否是超级管理员
	PRIMARY KEY (ID)
);


-- 角色表
CREATE TABLE SYS_ROLE (
	ID VARCHAR(100) NOT NULL, -- ID
	CODE VARCHAR(100) NOT NULL, -- 编码
	ROLE_NAME VARCHAR(50) NOT NULL , -- 角色名称
	REMARK LONGTEXT, -- 描述，备注
	DISPLAY_ORDER INT NULL , -- 展示顺序
	CREATOR_ID VARCHAR(100),-- 创建人ID
	UPDATOR_ID VARCHAR(100),-- 操作人ID
	CREATOR_NAME VARCHAR(100),-- 创建人名称
	OPERATOR_NAME VARCHAR(100),-- 操作人名称
	CREATE_TIME DATETIME,-- 创建时间
	OPERATE_TIME DATETIME,-- 修改时候
	STATUS BIT(1),-- 状态
	PRIMARY KEY (ID)
);

-- 资源权限表
CREATE TABLE sys_resource (
	ID BIGINT NOT NULL ,
	PARENTID BIGINT NULL ,
	PATH VARCHAR(255) ,
	RESOURCENAME VARCHAR(50) NOT NULL ,
	URL VARCHAR(200) ,
	URLPREFIX VARCHAR(200) ,
	REMARK TEXT ,
	ROUTETYPE VARCHAR(20) ,
	MODULEPATH TEXT ,
	IMAGE VARCHAR(255) ,
	RESOURCETYPE VARCHAR(20)  NOT NULL ,
	PERMISSION VARCHAR(100) ,
	DISPLAYORDER FLOAT(53) NULL ,
	CREATOR BIGINT NULL ,
	CREATETIME DATETIME NULL ,
	OPERATOR BIGINT NULL ,
	LASTUPDATETIME DATETIME NULL ,
	VALID BIT NULL ,
	NODELEVEL INT NULL ,
	MODULEMETHOD VARCHAR(20) ,
	URLTARGET VARCHAR(20) ,
	SYS BIT NOT NULL DEFAULT ((0)),
	CREATOR_ID VARCHAR(100),-- 创建人ID
	UPDATOR_ID VARCHAR(100),-- 操作人ID
	CREATOR_NAME VARCHAR(100),-- 创建人名称
	OPERATOR_NAME VARCHAR(100),-- 操作人名称
	CREATE_TIME DATETIME,-- 创建时间
	OPERATE_TIME DATETIME,-- 修改时候
	STATUS BIT(1),-- 状态
);